### ISSUE TITLE
itable didn't work in jupyter

### ISSUE THREAD

**Issue by SailingHe** [mwouts/itables#12] opened 2020-09-02 00:28 UTC
I installed itables(0.2.1),it successedly inbstalled and I insert  import itables.interactive ;
However,it didn't work,the dataframe didn't display.
The dataframe had data,when I use print or display(from ipython),the dataframe displayed;
I didn't know what's the matter.

**Comment by mwouts** [comment] 2020-09-02 08:11
Hi @SailingHe , do we agree that `itables` only work in Jupyter Notebook (not Lab) ?

If so, could you please
1. confirm that `itables` on [mybinder](https://mybinder.org/v2/gh/mwouts/itables/master?filepath=README.md) works for you
2. share the version of Jupyter Notebook that you are using
3. show us your browser logs - is there any error message there?

**Comment by SailingHe** [comment] 2020-09-06 00:45
I used it in jupyter notebook and the version is 5.7.8;
I don't understand the first reply(the binder?)
I guess the problem lies in the binder.The binder depend on package jupyter_contrib_nbextensions? 
I used jupyter notebook in an environment without internet ,when I tried to install the  jupyter_contrib_nbextensions from Compressed file(zip), An error occurred: No such file in C:\\users\\user_name\\AppData\\Local\\Temp\\pip-req-build-h0ron93p\\setup.py
I don't know how to install jupyter_contrib_nbextensions without internet

**Comment by mwouts** [comment] 2020-09-06 16:56
> I don't understand the first reply(the binder?)

My link above (mybinder) provides a notebook in which you can test `itables`.

> I used jupyter notebook in an environment without internet

Oh I see! That explains the problem: `itables` is based on `datatables.net` and requires an internet connection to download that library, every time you open a notebook.

**Comment by SailingHe** [comment] 2020-09-09 02:29
> Oh I see! That explains the problem: itables is based on datatables.net and requires an internet connection to download that library, every time you open a notebook.
could I download datatables.net to my computer which without internet?

**Comment by SailingHe** [comment] 2020-09-09 02:30
> Oh I see! That explains the problem: itables is based on datatables.net and requires an internet connection to download that library, every time you open a notebook.

could I download datatables.net to my computer which without internet?

**Comment by mwouts** [comment] 2021-12-22 21:32
Closing this as a duplicate of #8

**Closed by mwouts** 2021-12-22 21:32 UTC
